import React, { useState } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import { useNavigate } from "react-router-dom";
import { API_URL } from "../config"; // SERVER_URL not needed here

function AddProduct() {
  const navigate = useNavigate();

  const [product, setProduct] = useState({
    title: "",
    description: "",
    benefits: "",
  });
  const [images, setImages] = useState([]);

  const handleChange = (e) => {
    setProduct({ ...product, [e.target.name]: e.target.value });
  };

  const handleFileChange = (e) => {
    setImages(e.target.files);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const formData = new FormData();
      formData.append("title", product.title);
      formData.append("description", product.description);
      formData.append("benefits", product.benefits);
      // IMPORTANT: field name must match upload.array("images", 5)
      for (let i = 0; i < images.length; i++) {
        formData.append("images", images[i]);
      }

      const { data } = await axios.post(`${API_URL}products/add`, formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });

      // data should include productId (generated by backend)
      if (data?.productId) {
        toast.success(`✅ Product saved (ID: ${data.productId})`);
        // redirect admin straight to retailer view: /retailer/:productId
        navigate(`/retailer/${data.productId}`);
      } else {
        toast.success("✅ Product saved, but no productId returned");
      }

      // (Optional) reset local form state
      setProduct({ title: "", description: "", benefits: "" });
      setImages([]);
    } catch (error) {
      console.error(error);
      toast.error(
        error?.response?.data?.message || "❌ Failed to upload product"
      );
    }
  };

  return (
    <div className="max-w-lg mx-auto p-4 shadow-lg rounded-xl bg-white">
      <h2 className="text-xl font-bold mb-4">Add New Product</h2>
      <form onSubmit={handleSubmit} className="flex flex-col gap-4">
        <input
          type="text"
          name="title"
          placeholder="Product Title"
          value={product.title}
          onChange={handleChange}
          className="border p-2 rounded"
          required
        />

        <textarea
          name="description"
          placeholder="Product Description"
          value={product.description}
          onChange={handleChange}
          className="border p-2 rounded"
          required
        />

        <textarea
          name="benefits"
          placeholder="Product Benefits"
          value={product.benefits}
          onChange={handleChange}
          className="border p-2 rounded"
          required
        />

        <input
          type="file"
          name="images"
          multiple
          onChange={handleFileChange}
          className="border p-2 rounded"
          required
        />

        {/* Preview selected images */}
        <div className="flex gap-2 flex-wrap">
          {Array.from(images).map((file, idx) => (
            <img
              key={idx}
              src={URL.createObjectURL(file)}
              alt="preview"
              className="w-20 h-20 object-cover rounded"
            />
          ))}
        </div>

        <button
          type="submit"
          className="bg-blue-600 text-white py-2 rounded hover:bg-blue-700"
        >
          Upload Product
        </button>
      </form>
    </div>
  );
}

export default AddProduct;
